### PR TITLE
Added CCHub

### PR DESCRIPTION
**Pull request by sammysgame**
Hi 

I was a little unsure about the format to use for listing the tech hubs so I decided to create a pull request with one first, if accepted, then I can add others using the same format.

Regards,
Sam

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@sammysgame That's actually a nice format. I intended to list all the states from A - Z. But I can't do it alone, so if you can take a stab at it, that would be awesome!

**Comment by sammysgame** [comment]
@unicodeveloper I would very much love to work on it. Thanks

**Comment by unicodeveloper** [comment]
Awesome. Please send a PR when you are done. You can get the list of [tech-hubs here](https://techpoint.ng/2017/03/06/list-tech-hubs-across-nigeria/).

**Comment by sammysgame** [comment]
Thanks for the resource. Started working on it already.

**Pull request merged**
